-- This is the SQL script for setting up the DDL for the h2 database
-- In a typical project you would only distinguish between main and test for flyway SQLs
-- However, in this sample application we provde support for multiple databases in parallel
-- You can simply choose the DB of your choice by setting spring.profiles.active=XXX in config/application.properties
-- Assuming that the preconfigured user exists with according credentials using the included SQLs

CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1000000;

-- *** Restaurant ***
CREATE TABLE RESTAURANT (
  id BIGINT NOT NULL,
  modificationCounter INTEGER NOT NULL,
  restaurantName VARCHAR(255),
  address VARCHAR(255),
  mainLanguage VARCHAR(255)
);

ALTER TABLE RESTAURANT ADD CONSTRAINT PK_RESTAURANT PRIMARY KEY(id);

-- *** BinaryObject (BLOBs) ***
--CREATE TABLE BINARYOBJECT (
--  id BIGINT NOT NULL,
--  modificationCounter INTEGER NOT NULL,
--  data BLOB(2147483647),
--  size BIGINT NOT NULL,
--  mimetype VARCHAR(255),
--  PRIMARY KEY (ID)
--);

-- *** RevInfo (Commit log for envers audit trail) ***
CREATE TABLE REVINFO(
    id BIGINT NOT NULL generated by default as identity (start with 1),
    timestamp BIGINT NOT NULL,
    user VARCHAR(255)
);

